import { ipcRenderer, contextBridge } from 'electron'

contextBridge.exposeInMainWorld('electronAPI', {
  searchPlayer: (username: string) => ipcRenderer.invoke('search-player', username),
  savePlayer: (data: SavePlayerInput) => ipcRenderer.invoke('save-player', data),
  getAllPlayers: () => ipcRenderer.invoke('get-all-players'),
  getPlayerById: (id: number) => ipcRenderer.invoke('get-player-by-id', id),
  getAppInfo: () => ipcRenderer.invoke('get-app-info'),
  getStorageInfo: () => ipcRenderer.invoke('get-storage-info'),
  getRoomKnowledgeIndex: () => ipcRenderer.invoke('get-room-knowledge-index'),
  getRoomWallets: (roomKey: string, dealType?: RoomDealType) => ipcRenderer.invoke('get-room-wallets', roomKey, dealType),
  getRoomDeals: (roomKey: string, language: RoomLanguage, dealType?: RoomDealType) => ipcRenderer.invoke('get-room-deals', roomKey, language, dealType),
  getRoomCountryAvailability: (roomKey: string) => ipcRenderer.invoke('get-room-country-availability', roomKey),
  saveRoomProfile: (data: SaveRoomProfileInput) => ipcRenderer.invoke('save-room-profile', data),
  saveRoomDeal: (data: SaveRoomDealInput) => ipcRenderer.invoke('save-room-deal', data),
  saveRoomWallet: (data: SaveRoomWalletInput) => ipcRenderer.invoke('save-room-wallet', data),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  resolveTransaction: (input: ResolveTransactionInput) => ipcRenderer.invoke('resolve-transaction', input),
  convertUsdToEur: (amount: string) => ipcRenderer.invoke('convert-usd-to-eur', amount),
  getReleaseNotes: () => ipcRenderer.invoke('get-release-notes'),
  markReleaseNotesSeen: () => ipcRenderer.invoke('mark-release-notes-seen'),
  openExternalUrl: (url: string) => ipcRenderer.invoke('open-external-url', url),
  deletePlayer: (id: number) => ipcRenderer.invoke('delete-player', id),
  updateDefaultWallet: (id: number, wallet: string) => ipcRenderer.invoke('update-default-wallet', id, wallet),
  updateDefaultWalletDetails: (id: number, wallet: string, network: string) => ipcRenderer.invoke('update-default-wallet-details', id, wallet, network),
})
